# Generated by Django 3.2.6 on 2021-08-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alumnus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alumnus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.alumnus'),
            preserve_default=False,
        ),
    ]
